name: Publish
on:
  release:
    types: [published]
permissions:
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      ORG: ${{ vars.PUBLISH_ORG != '' && vars.PUBLISH_ORG || 'sageveil' }}
    steps:
      - name: Parse tag to port and version
        id: parse
        shell: bash
        run: |
          set -euo pipefail
          TAG="${{ github.event.release.tag_name }}"
          if [[ "$TAG" =~ ^@[^/]+/([^@]+)@([0-9]+\.[0-9]+\.[0-9]+([-\.][A-Za-z0-9\.]+)?)$ ]]; then
            PORT="${BASH_REMATCH[1]}"
            VERSION="${BASH_REMATCH[2]}"
            echo "port=$PORT" >> "$GITHUB_OUTPUT"
            echo "version=$VERSION" >> "$GITHUB_OUTPUT"
            echo "Tag OK. port=$PORT version=$VERSION"
          else
            echo "Invalid tag format: $TAG"
            echo "Expected @scope/port@version. Example @sageveil/tmux@1.0.0"
            exit 1
          fi
